services:
  frontend:
    image: mavoka-fe-2025-dev-img:${GITHUB_SHA}
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      project: mavoka-fe-2025
      environment: dev
    restart: unless-stopped
    deploy:
      mode: replicated
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.1"
          memory: "256M"
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        order: start-first
    networks:
      - core
      - mavoka_dev

networks:
  core:
    external: true
  mavoka_dev:
    external: true
